name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - name: Restore Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod              # Module download cache
          ~/.cache/go-build         # Build cache (Linux)
          ~/Library/Caches/go-build # Build cache (Mac)
          '%LocalAppData%\go-build' # Build cache (Windows)
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: |
        go build -o ./bin/yakk -v ./cmd/yakk/.
        go build -o ./bin/yakkserver -v ./cmd/yakkserver/.
        ls -a

    # - name: Test
    #   run: go test -v ./...

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        # Artifact name
        name: artifact-linux
        # A file, directory or wildcard pattern that describes what to upload
        path: bin

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - name: Restore Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod              # Module download cache
          ~/.cache/go-build         # Build cache (Linux)
          ~/Library/Caches/go-build # Build cache (Mac)
          '%LocalAppData%\go-build' # Build cache (Windows)
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: |
        go build -o ./bin/yakk -v ./cmd/yakk/.
        go build -o ./bin/yakkserver -v ./cmd/yakkserver/.

    # - name: Test
    #   run: go test -v ./...

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        # Artifact name
        name: artifact-windows
        # A file, directory or wildcard pattern that describes what to upload
        path: bin
