name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - name: Restore Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod              # Module download cache
          ~/.cache/go-build         # Build cache (Linux)
          ~/Library/Caches/go-build # Build cache (Mac)
          '%LocalAppData%\go-build' # Build cache (Windows)
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Prepare artifact folder
      run: |
        mkdir ./bin
        mkdir ./bin/yakk
        mkdir ./bin/yakkserver

    - name: Build Linux 386
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=386 go build -o ./bin/linux-386/yakk ./cmd/yakk/.
        CGO_ENABLED=0 GOOS=linux GOARCH=386 go build -o ./bin/linux-386/yakkserver ./cmd/yakkserver/.

        zip -rmj ./bin/yakk/yakk-linux-386.zip ./bin/linux-386/yakk
        zip -rmj ./bin/yakkserver/yakkserver-linux-386.zip ./bin/linux-386/yakkserver

    - name: Build Linux AMD 64
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ./bin/linux-amd64/yakk ./cmd/yakk/.
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ./bin/linux-amd64/yakkserver ./cmd/yakkserver/.

        zip -rmj ./bin/yakk/yakk-linux-amd64.zip ./bin/linux-amd64/yakk
        zip -rmj ./bin/yakkserver/yakkserver-linux-amd64.zip ./bin/linux-amd64/yakkserver

    - name: Build Linux ARM
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=arm go build -o ./bin/linux-arm/yakk ./cmd/yakk/.
        CGO_ENABLED=0 GOOS=linux GOARCH=arm go build -o ./bin/linux-arm/yakkserver ./cmd/yakkserver/.

        zip -rmj ./bin/yakk/yakk-linux-arm.zip ./bin/linux-arm/yakk
        zip -rmj ./bin/yakkserver/yakkserver-linux-arm.zip ./bin/linux-arm/yakkserver

    - name: Install Android toolchain
      run: |
        sudo apt-get install gcc-arm-linux-gnueabi 

    - name: Build Android ARM
      run: |
        CGO_ENABLED=1 GOOS=android GOARCH=arm CC=arm-linux-gnueabi-gcc go build -o ./bin/android-arm/yakk -v ./cmd/yakk/.
        zip -rmj ./bin/yakk/yakk-android-arm.zip ./bin/android-arm/yakk

    - name: Build Android ARM 64
      run: |
        CGO_ENABLED=1 GOOS=android GOARCH=arm CC=arm-linux-gnueabi-gcc go build -o ./bin/android-arm64/yakk -v ./cmd/yakk/.
        zip -rmj ./bin/yakk/yakk-android-arm64.zip ./bin/android-arm64/yakk

    - name: Build Windows x86
      run: |
        CGO_ENABLED=0 GOOS=windows GOARCH=386 go build -o ./bin/windows-386/yakk.exe ./cmd/yakk/.
        CGO_ENABLED=0 GOOS=windows GOARCH=386 go build -o ./bin/windows-386/yakkserver.exe ./cmd/yakkserver/.

        zip -rmj ./bin/yakk/yakk-windows-386.zip ./bin/windows-386/yakk.exe
        zip -rmj ./bin/yakkserver/yakkserver-windows-386.zip ./bin/windows-386/yakkserver.exe

    - name: Build Windows amd64
      run: |
        CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o ./bin/windows-amd64/yakk.exe ./cmd/yakk/.
        CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o ./bin/windows-amd64/yakkserver.exe ./cmd/yakkserver/.

        zip -rmj ./bin/yakk/yakk-windows-amd64.zip ./bin/windows-amd64/yakk.exe
        zip -rmj ./bin/yakkserver/yakkserver-windows-amd64.zip ./bin/windows-amd64/yakkserver.exe

    # - name: Test
    #   run: go test -v ./...

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        # Artifact name
        name: artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: bin

  # build-windows:
  #   name: Build Windows
  #   runs-on: windows-latest
  #   steps:

  #   - name: Set up Go 1.x
  #     uses: actions/setup-go@v2
  #     with:
  #       go-version: ^1.13

  #   - name: Check out code into the Go module directory
  #     uses: actions/checkout@v2
    
  #   - name: Restore Cache
  #     uses: actions/cache@v2
  #     with:
  #       path: |
  #         ~/go/pkg/mod              # Module download cache
  #         ~/.cache/go-build         # Build cache (Linux)
  #         ~/Library/Caches/go-build # Build cache (Mac)
  #         '%LocalAppData%\go-build' # Build cache (Windows)
  #       key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
  #       restore-keys: |
  #         ${{ runner.os }}-go-

  #   - name: Get dependencies
  #     run: |
  #       go get -v -t -d ./...

  #   - name: Build
  #     run: |
  #       go build -o ./bin/yakk -v ./cmd/yakk/.
  #       go build -o ./bin/yakkserver -v ./cmd/yakkserver/.

  #   # - name: Test
  #   #   run: go test -v ./...

  #   - name: Upload Build Artifact
  #     uses: actions/upload-artifact@v2.2.1
  #     with:
  #       # Artifact name
  #       name: artifact-windows
  #       # A file, directory or wildcard pattern that describes what to upload
  #       path: bin
